#setwd("~/Desktop/Lab/Joseline")
inputvcf = "ChrALL.vcf"
inputnames = "SummerGenomics/samplenames.csv"
##input names file generated by running
# python vcf_manip/get_labels_pops.py -m metadata/label_match.csv -i samplenames.txt -o samplenames.csv

library(vcfR)
library(adegenet)

label_map <- read.csv(inputnames)


vcf <- read.vcfR(inputvcf)
mybov <- vcfR2genind(vcf)

indNames(mybov)<-label_map$ind_name
pop(mybov)<-label_map$pop


x.cows <- tab(mybov, freq=TRUE, NA.method="mean")
pca.cows <- dudi.pca(df = x.cows, center = TRUE, scale = FALSE, nf = 3, scannf = FALSE)
s.label(pca.cows$li)

s.class(pca.cows$li, fac=pop(mybov),col=transp(funky(15),.6),axesel=FALSE, cstar=0, cpoint=3)


#--------------------------
#--------Run a snapclust even though they come out very odd...

grp.ini <- find.clusters(mybov, n.clust=12, n.pca=50)

## run EM algo
res <- snapclust(mybov, 12, pop.ini = grp.ini$grp, hybrids =FALSE)


## plot result
compoplot(res, show.lab=TRUE)
